loans_cols =   ['Mortgage_Loan', 
                'Personal_Loan', 
                'Credit-Builder_Loan', 
                'Debt_Consolidation_Loan', 
                'Payday_Loan',
                'Auto_Loan',
                'Not_Specified_Loan',
                'Home_Equity_Loan',
                'Student_Loan']

# X_reduced_num_cols =   ['Age',
#                         'Annual_Income',
#                         'Monthly_Inhand_Salary',
#                         'Num_Bank_Accounts',
#                         'Num_Credit_Card',
#                         'Interest_Rate',
#                         'Num_of_Loan',
#                         'Delay_from_due_date',
#                         'Num_of_Delayed_Payment',
#                         'Changed_Credit_Limit',
#                         'Num_Credit_Inquiries',
#                         'Outstanding_Debt',
#                         'Credit_History_Age',
#                         'Amount_invested_monthly',
#                         'Monthly_Balance',
#                         'Mortgage_Loan',
#                         'Personal_Loan',
#                         'Credit-Builder_Loan',
#                         'Debt_Consolidation_Loan',
#                         'Payday_Loan',
#                         'Auto_Loan',
#                         'Not_Specified_Loan',
#                         'Home_Equity_Loan',
#                         'Student_Loan']

X_reduced_cat_cols =   ['Credit_Mix', 
                        'Payment_of_Min_Amount', 
                        'Payment_Behaviour']

num_cols_without_loans =   ['Age',
                            'Annual_Income',
                            'Monthly_Inhand_Salary',
                            'Num_Bank_Accounts',
                            'Num_Credit_Card',
                            'Interest_Rate',
                            'Num_of_Loan',
                            'Delay_from_due_date',
                            'Num_of_Delayed_Payment',
                            'Changed_Credit_Limit',
                            'Num_Credit_Inquiries',
                            'Outstanding_Debt',
                            'Credit_History_Age',
                            'Amount_invested_monthly',
                            'Monthly_Balance']